"""Add dietplan table

Revision ID: d9f5dd34f4bc
Revises: e9a452625402
Create Date: 2024-10-04 18:50:49.805878

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f5dd34f4bc'
down_revision: Union[str, None] = 'e9a452625402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dietplan',
    sa.Column('diet_plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dietitian_id', sa.Integer(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('plan_status', sqlmodel.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['dietitian_id'], ['dietitian.dietitian_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('diet_plan_id')
    )
    op.drop_index('ix_permissions_role_id', table_name='permissions')
    op.drop_index('ix_usersroles_role_id', table_name='usersroles')
    op.drop_index('ix_usersroles_user_id', table_name='usersroles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_usersroles_user_id', 'usersroles', ['user_id'], unique=False)
    op.create_index('ix_usersroles_role_id', 'usersroles', ['role_id'], unique=False)
    op.create_index('ix_permissions_role_id', 'permissions', ['role_id'], unique=False)
    op.drop_table('dietplan')
    # ### end Alembic commands ###
